channels:
  - conda-forge
dependencies:
  - bokeh
  - pandas
  - scikit-learn
  - shapely
  - alphashape
  - astropy=5 # warns that TCRPX11 etc might be removed from headers in future versions 
  - bs4
  - python-magic
  - kneed
  - hdbscan
  - pillow
  - pip
  - pip:
    - pca
