channels:
  - conda-forge
dependencies:
  - python=3.9
  - bokeh
  - pandas
  - scikit-learn
  - shapely
  - alphashape
  - astropy
  - bs4
  - python-magic
  - kneed
  - hdbscan
  - pip
  - pip:
    - pca
